### ISSUE TITLE
Olric nil pointer panic on last line of internal transport listenAndServe 

### ISSUE THREAD

**Issue by ForestJohnson** [caddyserver/cache-handler#11]
in my thread about caching  in caddy to I posted [a reply](https://caddy.community/t/state-of-http-caching-in-caddy-2/11564/8?u=forest_johnson) where I  detailed an exception I was getting from olric when I attempted to run my   `GOARCH=arm` xcaddy build of  caddy 2.4.0 beta + this cache-handler package.

`forest@thingpad:~/Desktop/git/caddy/cmd/caddy$ GOARCH=arm ~/Desktop/programs/xcaddy/xcaddy build --with github.com/caddyserver/cache-handler`

...

heres the Caddyfile i used:

```
{
    cache {
        olric_config olricd.yml
    }
}

localhost

route /cache-s-maxage {
    cache
    header Cache-Control "s-maxage=5, max-age=1"
    respond "Hello, s-maxage!"
}

route /cache-max-age {
    cache
    header Cache-Control "max-age=60"
    respond "Hello, max-age!"
}

```

and heres my olricd.yml file:

```
# Copied from https://github.com/buraksezer/olric/blob/master/cmd/olricd/olricd.yaml
olricd:
  bindAddr: "0.0.0.0"
  bindPort: 3320
  serializer: "msgpack"
  keepAlivePeriod: "300s"
  requestTimeout: "5s"
  partitionCount:  13
  replicaCount: 1
  writeQuorum: 1
  readQuorum: 1
  readRepair: false
  replicationMode: 0 # sync mode. for async, set 1
  tableSize: 1048576 # 1MB in bytes
  memberCountQuorum: 1

logging:
  verbosity: 6
  level: "DEBUG"
  output: "stderr"

memberlist:
  environment: "local"
  bindAddr: "0.0.0.0"
  bindPort: 3322
  enableCompression: false
  joinRetryInterval: "1ms"
  maxJoinAttempts: 1

```

Heres what it printed

```
root@odroidxu4:~# ./caddy2 run
2021/02/18 22:51:21.269	INFO	using adjacent Caddyfile
[WARNING][caddyfile] Caddyfile:1: input is not formatted with 'caddy fmt'
2021/02/18 22:51:21.276	INFO	admin	admin endpoint started	{"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2021/02/18 22:51:21.276	INFO	http	server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS	{"server_name": "srv0", "https_port": 443}
2021/02/18 22:51:21.276	INFO	http	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2021/02/18 22:51:21.276	INFO	tls.cache.maintenance	started background certificate maintenance	{"cache": "0x2459180"}
2021/02/18 16:51:21 [INFO] Join completed. Synced with 0 initial nodes => olric.go:304
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11db8]

goroutine 85 [running]:
runtime/internal/atomic.goStore64(0x25ac014, 0xd, 0x0)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:144 +0x1c
github.com/buraksezer/olric.(*Olric).setOwnedPartitionCount(0x25ac000)
	/home/forest/go/pkg/mod/github.com/buraksezer/olric@v0.3.5/routing.go:452 +0x15c
github.com/buraksezer/olric.(*Olric).updateRoutingOperation(0x25ac000, 0x13915e8, 0x22281b0, 0x13915e8, 0x2228180)
	/home/forest/go/pkg/mod/github.com/buraksezer/olric@v0.3.5/routing.go:496 +0x33c
github.com/buraksezer/olric.(*Olric).requestDispatcher(0x25ac000, 0x13915e8, 0x22281b0, 0x13915e8, 0x2228180)
	/home/forest/go/pkg/mod/github.com/buraksezer/olric@v0.3.5/olric.go:265 +0xac
github.com/buraksezer/olric/internal/transport.(*Server).processMessage(0x22d8a80, 0xa694d568, 0x26cc690, 0x25fa6d4, 0x20cc540, 0x0, 0x0)
	/home/forest/go/pkg/mod/github.com/buraksezer/olric@v0.3.5/internal/transport/server.go:194 +0x294
github.com/buraksezer/olric/internal/transport.(*Server).processConn(0x22d8a80, 0xa694d568, 0x26cc690)
	/home/forest/go/pkg/mod/github.com/buraksezer/olric@v0.3.5/internal/transport/server.go:218 +0x108
created by github.com/buraksezer/olric/internal/transport.(*Server).listenAndServe
	/home/forest/go/pkg/mod/github.com/buraksezer/olric@v0.3.5/internal/transport/server.go:257 +0xd8
```

for your viewing pleasure, here is a small section of [ /home/forest/go/pkg/mod/github.com/buraksezer/olric@v0.3.5/internal/transport/server.go annotated with line numbers](https://paste.cyberia.club/~forest/515f9e6d7ec69fe804dca6ad5ed7cb030dce3fed)

**Comment by buraksezer** [comment]
Hi @ForestJohnson thank you for reporting. I'm on it. I have never tried to compile Olric with `GOARCH=arm`. Actually it's intended for 64 bit systems (more specifically containers and VMs). There may be many problems on a 32-bit platform.

**Comment by francislavoie** [comment]
@gc-ss this issue isn't relevant anymore because this module was rewritten to use souin (which wraps olric) instead of olric directly
