### ISSUE TITLE
fatal errors are not logged

### ISSUE THREAD

**Issue by tve** [caddyserver/cache-handler#36]
I'm trying to use the cache handler and it wasn't working. The symptom:
```
tve@cloud /h/caddy> curl -o /dev/null 'https://example.com/data/binary/tagVisits'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

Only after I turned on debug logging I got:
```
Oct 10 09:12:24 cloud caddy[2743409]: {"level":"debug","ts":1665418344.1734848,"logger":"http.stdlib
","msg":"http2: panic serving 0.0.0.0:56316: Impossible to set value into Badger, Value with si
ze 2779485 exceeded 1048576 limit. Value:\n00000000  48 54 54 50 2f 30 2e 30  20 32 30 30 20 4f 4b 0
d  |HTTP/0.0 200 OK.|\n00000010  0a 41 6c 74 2d 53 76 63  3a 20 68 33 3d 22 3a 34  |.Alt-Svc: h3=\":
```

1. why is this error not logged without debug?
2. why is there a panic?
3. it looks to me like this 'badger' thing needs some config to cache >1MB? do I now need to go on a quest to figure out what badger is, why http.cache uses it, and how to configure it?

**Comment by mholt** [comment]
What is the full error message? It should have a stack trace.

Code somewhere is panicking -- it definitely should not be -- and the std lib is catching it. Because the Go standard library is catching it and emitting the log, the log is treated as DEBUG level, as std lib logs are usually noise in the context of Caddy.

**Comment by tve** [comment]
> Because the Go standard library is catching it and emitting the log, the log is treated as DEBUG level, as std lib logs are usually noise in the context of Caddy.

Maybe it would be a good idea to pattern match stack backtraces and emit some error log entry to indicate that something is gone horribly awry?

Here's the backtrace as it appears in the log:
```
goroutine 1500 [running]:\nnet/
http.(*http2serverConn).runHandler.func1()\n\tnet/http/h2_bundle.go:5904 +0x125\npanic({0x19dc500, 0
xc000105d60})\n\truntime/panic.go:884 +0x212\ngithub.com/darkweak/souin/cache/providers.(*Badger).Se
t(0xc000104130, {0xc00075ba10, 0x2e}, {0xc01eb84000, 0x2a695d, 0x400000}, {{0x34630b8a000}, {0x2ecbb
98, 0x0, 0x0}, ...}, ...)\n\tgithub.com/darkweak/souin@v1.6.6/cache/providers/badgerProvider.go:138 
+0x229\ngithub.com/darkweak/souin/rfc.(*VaryTransport).SetCache(0xc000124bd0, {0xc00075ba10, 0x2e}, 
0xc000439a70)\n\tgithub.com/darkweak/souin@v1.6.6/rfc/transport.go:85 +0x263\ngithub.com/darkweak/so
uin/rfc.validateVary.func1({0x20ad6c0, 0xc009bead80})\n\tgithub.com/darkweak/souin@v1.6.6/rfc/vary.g
o:37 +0x198\ngithub.com/darkweak/souin/rfc.(*cachingReadCloser).Read(0xc000288f40, {0xc01e1e080a, 0x
46000?, 0xa37f6})\n\tgithub.com/darkweak/souin@v1.6.6/rfc/standalone.go:352 +0x177\nio.ReadAll({0x7f
b7e1063b40, 0xc000288f40})\n\tio/io.go:661 +0xfe\nio/ioutil.ReadAll(...)\n\tio/ioutil/ioutil.go:27\n
github.com/darkweak/souin/plugins.(*CustomWriter).Send(0xc00013d220)\n\tgithub.com/darkweak/souin@v1
.6.6/plugins/base.go:68 +0x20f\ngithub.com/caddyserver/cache-handler.(*SouinCaddyPlugin).ServeHTTP.f
unc1({0x1a66840?, 0xc00003a060?}, 0x1d5c566?)\n\tgithub.com/caddyserver/cache-handler@v0.2.0/httpcac
he.go:105 +0x10f\ngithub.com/darkweak/souin/plugins.DefaultSouinPluginCallback({0x20bc5c0, 0xc00013d
220}, 0xc00053ea00, {0x20cd618, 0xc0005a87e0}, {0x0, 0x0}, 0xc00044f4f0)\n\tgithub.com/darkweak/soui
n@v1.6.6/plugins/base.go:178 +0x6df\ngithub.com/caddyserver/cache-handler.(*SouinCaddyPlugin).ServeH
TTP(0xc00f25dd00, {0x7fb7e104cae0?, 0xc009954ae0}, 0xc00053e400, {0x20b3dc0, 0xc00013d1e0})\n\tgithu
b.com/caddyserver/cache-handler@v0.2.0/httpcache.go:93 +0x69a\ngithub.com/caddyserver/caddy/v2/modul
es/caddyhttp.wrapMiddleware.func1.1({0x7fb7e104cae0?, 0xc009954ae0?}, 0x20b3dc0?)\n\tgithub.com/cadd
yserver/caddy/v2@v2.6.1/modules/caddyhttp/routes.go:290 +0x42\ngithub.com/caddyserver/caddy/v2/modul
es/caddyhttp.HandlerFunc.ServeHTTP(0x20b3dc0?, {0x7fb7e104cae0?, 0xc009954ae0?}, 0x0?)\n\tgithub.com
/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v
2/modules/caddyhttp.wrapRoute.func1.1({0x7fb7e104cae0, 0xc009954ae0}, 0xc00053e400)\n\tgithub.com/ca
ddyserver/caddy/v2@v2.6.1/modules/caddyhttp/routes.go:259 +0x3a8\ngithub.com/caddyserver/caddy/v2/mo
dules/caddyhttp.HandlerFunc.ServeHTTP(0xc00010b8c0?, {0x7fb7e104cae0?, 0xc009954ae0?}, 0x20b3dc0?)\n
\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyse
rver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc008fe1d40, {0x7fb7e104cae0, 0xc009954ae0}, 
0x1?, {0x20b3dc0, 0xc00013d160})\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/subrout
e.go:74 +0x6d\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7fb7e104c
ae0?, 0xc009954ae0?}, 0x20b3dc0?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/routes
.go:290 +0x42\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x20b3dc0?, {
0x7fb7e104cae0?, 0xc009954ae0?}, 0x0?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/c
addyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7fb7e10
4cae0, 0xc009954ae0}, 0xc00053e400)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/rout
es.go:259 +0x3a8\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1a66840?
, {0x7fb7e104cae0?, 0xc009954ae0?}, 0xe?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhtt
p/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7fb7
e104cae0, 0xc009954ae0}, 0xc00053e400)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/r
outes.go:227 +0x336\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0094
05500?, {0x7fb7e104cae0?, 0xc009954ae0?}, 0x20b3dc0?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modu
les/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).S
erveHTTP(0xc008fe1a20, {0x7fb7e104cae0, 0xc009954ae0}, 0x19d8201?, {0x20b3dc0, 0x1e04120})\n\tgithub
.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/subroute.go:74 +0x6d\ngithub.com/caddyserver/cadd
y/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7fb7e104cae0?, 0xc009954ae0?}, 0x20b3dc0?)\n\tgithu
b.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/routes.go:290 +0x42\ngithub.com/caddyserver/cadd
y/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x20b3dc0?, {0x7fb7e104cae0?, 0xc009954ae0?}, 0xc0096e3
498?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/
caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7fb7e104cae0, 0xc009954ae0}, 0xc00053e40
0)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/routes.go:259 +0x3a8\ngithub.com/cadd
yserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2?, {0x7fb7e104cae0?, 0xc009954ae0?}, 0x7
fb8087b85b8?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngit
hub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x40dca7?, {0x7fb7e104ca
e0?, 0xc009954ae0?}, 0x1?, {0x20b3dc0?, 0xc00013c960?})\n\tgithub.com/caddyserver/caddy/v2@v2.6.1/mo
dules/caddyhttp/server.go:370 +0x252\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wr
apPrimaryRoute.func1({0x7fb7e104cae0?, 0xc009954ae0?}, 0x4cab37?)\n\tgithub.com/caddyserver/caddy/v2
@v2.6.1/modules/caddyhttp/server.go:346 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.Han
dlerFunc.ServeHTTP(0xc00937f1e0?, {0x7fb7e104cae0?, 0xc009954ae0?}, 0xc00053e400?)\n\tgithub.com/cad
dyserver/caddy/v2@v2.6.1/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/mo
dules/caddyhttp.(*Server).ServeHTTP(0xc00010ab40, {0x20bfbc0, 0xc000124fe0}, 0xc00053e400)\n\tgithub
.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/server.go:282 +0xb55\nnet/http.serverHandler.Serv
eHTTP({0x3bf1555da0ee5502?}, {0x20bfbc0, 0xc000124fe0}, 0xc00053e200)\n\tnet/http/server.go:2947 +0x
30c\nnet/http.initALPNRequest.ServeHTTP({{0x20c1978?, 0xc009954690?}, 0xc009445c00?, {0xc0001f6f00?}
}, {0x20bfbc0, 0xc000124fe0}, 0xc00053e200)\n\tnet/http/server.go:3556 +0x245\nnet/http.(*http2serve
rConn).runHandler(0xffd60e56fcd40e?, 0x2b00000200a20000?, 0x569aaa0956020042?, 0xa42b0000a1ab09?)\n\
tnet/http/h2_bundle.go:5911 +0x78\ncreated by net/http.(*http2serverConn).processHeaders\n\tnet/http
/h2_bundle.go:5641 +0x5b9"}
```

**Comment by tve** [comment]
I'm getting what looks like the same error using cdp-cache:
```
Oct 10 11:43:37 cloud caddy[2786696]: panic: interface conversion: interface {} is nil, not *caddyhttp.Server
Oct 10 11:43:37 cloud caddy[2786696]: goroutine 83 [running]:
Oct 10 11:43:37 cloud caddy[2786696]: github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).reverseProxy(0xc000141520, {0x1f29480?, 0xc00003e9b0}, 0xc0006af400, 0xc0006af300, 0xc00045c5c0, {0xc000334ae0, {0x1b6ce9f, 0x3}, {0xc0004be793, ...}, ...}, ...)
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/reverseproxy/reverseproxy.go:774 +0x1a45
Oct 10 11:43:37 cloud caddy[2786696]: github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).proxyLoopIteration(0xc000141520, 0xc0006af400, 0x4?, {0x1f29480, 0xc00003e9b0}, {0x0, 0x0}, {0xc0c937d64915b858, 0xbc371a11f, 0x2c31640}, ...)
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/reverseproxy/reverseproxy.go:570 +0xf05
Oct 10 11:43:37 cloud caddy[2786696]: github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).ServeHTTP(0xc000141520, {0x1f29480, 0xc00003e9b0}, 0xc0006af300, {0x1f1f060, 0xc00045c7e0})
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/reverseproxy/reverseproxy.go:478 +0x3da
Oct 10 11:43:37 cloud caddy[2786696]: github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x1f29480?, 0xc00003e9b0?}, 0x1f1f060?)
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/routes.go:290 +0x42
Oct 10 11:43:37 cloud caddy[2786696]: github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1f1f060?, {0x1f29480?, 0xc00003e9b0?}, 0x100?)
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/caddyhttp.go:58 +0x2f
Oct 10 11:43:37 cloud caddy[2786696]: github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1f29480, 0xc00003e9b0}, 0xc0006af300)
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/routes.go:259 +0x3a8
Oct 10 11:43:37 cloud caddy[2786696]: github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005ad230?, {0x1f29480?, 0xc00003e9b0?}, 0xc00044e890?)
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/caddyserver/caddy/v2@v2.6.1/modules/caddyhttp/caddyhttp.go:58 +0x2f
Oct 10 11:43:37 cloud caddy[2786696]: github.com/sillygod/cdp-cache.(*Handler).fetchUpstream.func1(0xc0006af200, 0x0?)
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/sillygod/cdp-cache@v0.4.6/handler.go:124 +0x2ac
Oct 10 11:43:37 cloud caddy[2786696]: created by github.com/sillygod/cdp-cache.(*Handler).fetchUpstream
Oct 10 11:43:37 cloud caddy[2786696]:         github.com/sillygod/cdp-cache@v0.4.6/handler.go:103 +0x26f
Oct 10 11:43:37 cloud systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by PythonLinks** [comment]
how did you compile cdp-cache?  Which version of go?  What command?

What is your caddy file. ?

**Comment by tve** [comment]
> how did you compile cdp-cache? Which version of go? What command?
> 
> What is your caddy file. ?

Please ignore (I've deleted the comment I had made), I got mixed up and thought the backtraces were the same. The crash with cdp-cache was due to using caddy 2.5.1.

**Comment by darkweak** [comment]
Can you retry with the latest release please?
