### ISSUE TITLE
Panic on incorrect badger configuration

### ISSUE THREAD

**Issue by jvns** [caddyserver/cache-handler#55]
I configured a cache handler like this:
```
    cache {
        badger {
            configuration {
                 Dir ""
		 ValueDir ""
		 InMemory true
            }
        }
    }

```

and when I make a request to a cached resource, I get this panic:

```
Jul 17 12:41:42 dynamicsites caddy[3505454]: {"level":"debug","ts":1689597702.9780827,"logger":"http.stdlib","msg":"http2: panic serving 162.243.172.248:43536: runtime error: invalid memory address or nil pointer dereference\ngoroutine 80 [running]:\nnet/http.(*http2serverConn).runHandler.func1()\n\tnet/http/h2_bundle.go:6042 +0x145\npanic({0x1d4fc00, 0x34b9f80})\n\truntime/panic.go:884 +0x213\ngithub.com/dgraph-io/badger/v3.(*DB).IsClosed(...)\n\tgithub.com/dgraph-io/badger/v3@v3.2103.5/db.go:537\ngithub.com/dgraph-io/badger/v3.(*DB).View(0x0?, 0x0?)\n\tgithub.com/dgraph-io/badger/v3@v3.2103.5/txn.go:795 +0x2f\ngithub.com/darkweak/souin/pkg/storage.(*Badger).Prefix(0x0?, {0xc0000c2e80?, 0x0?}, 0xc00072ad80?)\n\tgithub.com/darkweak/souin@v1.6.36/pkg/storage/badgerProvider.go:127 +0x6c\ngithub.com/darkweak/souin/pkg/middleware.(*SouinBaseHandler).ServeHTTP(0xc00016c000, {0x2529b30, 0xc0004e88d8}, 0xc0002f9d00, 0xc000681c00)\n\tgithub.com/darkweak/souin@v1.6.36/pkg/middleware/middleware.go:311 +0x7dd\ngithub.com/caddyserver/cache-handler.(*SouinCaddyMiddleware).ServeHTTP(0xc00019b2c0, {0x2529b30, 0xc0004e88d8}, 0xc0002f9d00, {0x251be60?, 0xc0009ffe30})\n\tgithub.com/caddyserver/cache-handler@v0.7.0/httpcache.go:81 +0xb3\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2529b30?, 0xc0004e88d8?}, 0x251be60?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:290 +0x42\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x251be60?, {0x2529b30?, 0xc0004e88d8?}, 0x0?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:259 +0x3a8\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00060b680?, {0x2529b30?, 0xc0004e88d8?}, 0x251be60?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0004fbba0, {0x2529b30, 0xc0004e88d8}, 0x1c94401?, {0x251be60, 0x22776b8})\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/subroute.go:74 +0x6d\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2529b30?, 0xc0004e88d8?}, 0x251be60?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:290 +0x42\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x251be60?, {0x2529b30?, 0xc0004e88d8?}, 0xc000438c78?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:259 +0x3a8\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1d38640?, {0x2529b30?, 0xc0004e88d8?}, 0xe?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1d38640?, {0x2529b30?, 0xc0004e88d8?}, 0xe?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1d38640?, {0x2529b30?, 0xc0004e88d8?}, 0xe?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0006524a0?, {0x2529b30?, 0xc0004e88d8?}, 0x1f3be40?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x0?, {0x2529b30?, 0xc0004e88d8?}, 0xc0006524a0?, {0x251be60?, 0xc00008a720?})\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:388 +0x252\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x2529b30?, 0xc0004e88d8?}, 0x4d59d7?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:364 +0x3b\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005fb6c0?, {0x2529b30?, 0xc0004e88d8?}, 0xc0002f9d00?)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0002dd400, {0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)\n\tgithub.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:300 +0xb66\nnet/http.serverHandler.ServeHTTP({0x1000?}, {0x2529b30, 0xc0004e88d8}, 0xc0002f9b00)\n\tnet/http/server.go:2936 +0x316\nnet/http.initALPNRequest.ServeHTTP({{0x252b6c8?, 0xc0009ff110?}, 0xc0005c4380?, {0xc0003e4a50?}}, {0x2529b30, 0xc0004e88d8}, 0xc0002f9b00)\n\tnet/http/server.go:3545 +0x245\nnet/http.(*http2serverConn).runHandler(0x25238d0?, 0x352c968?, 0x0?, 0x0?)\n\tnet/http/h2_bundle.go:6049 +0x83\ncreated by net/http.(*http2serverConn).processHeaders\n\tnet/http/h2_bundle.go:5762 +0x68a"}
```

Here's the stack trace formatted a little more nicely:

```
http2: panic serving 162.243.172.248:43536: runtime error: invalid memory address or nil pointer dereference
goroutine 80 [running]:
net/http.(*http2serverConn).runHandler.func1()
	net/http/h2_bundle.go:6042 +0x145
panic({0x1d4fc00, 0x34b9f80})
	runtime/panic.go:884 +0x213
github.com/dgraph-io/badger/v3.(*DB).IsClosed(...)
	github.com/dgraph-io/badger/v3@v3.2103.5/db.go:537
github.com/dgraph-io/badger/v3.(*DB).View(0x0?, 0x0?)
	github.com/dgraph-io/badger/v3@v3.2103.5/txn.go:795 +0x2f
github.com/darkweak/souin/pkg/storage.(*Badger).Prefix(0x0?, {0xc0000c2e80?, 0x0?}, 0xc00072ad80?)
	github.com/darkweak/souin@v1.6.36/pkg/storage/badgerProvider.go:127 +0x6c
github.com/darkweak/souin/pkg/middleware.(*SouinBaseHandler).ServeHTTP(0xc00016c000, {0x2529b30, 0xc0004e88d8}, 0xc0002f9d00, 0xc000681c00)
	github.com/darkweak/souin@v1.6.36/pkg/middleware/middleware.go:311 +0x7dd
github.com/caddyserver/cache-handler.(*SouinCaddyMiddleware).ServeHTTP(0xc00019b2c0, {0x2529b30, 0xc0004e88d8}, 0xc0002f9d00, {0x251be60?, 0xc0009ffe30})
	github.com/caddyserver/cache-handler@v0.7.0/httpcache.go:81 +0xb3
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2529b30?, 0xc0004e88d8?}, 0x251be60?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:290 +0x42
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x251be60?, {0x2529b30?, 0xc0004e88d8?}, 0x0?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:259 +0x3a8
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00060b680?, {0x2529b30?, 0xc0004e88d8?}, 0x251be60?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0004fbba0, {0x2529b30, 0xc0004e88d8}, 0x1c94401?, {0x251be60, 0x22776b8})
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/subroute.go:74 +0x6d
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2529b30?, 0xc0004e88d8?}, 0x251be60?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:290 +0x42
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x251be60?, {0x2529b30?, 0xc0004e88d8?}, 0xc000438c78?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:259 +0x3a8
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1d38640?, {0x2529b30?, 0xc0004e88d8?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1d38640?, {0x2529b30?, 0xc0004e88d8?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1d38640?, {0x2529b30?, 0xc0004e88d8?}, 0xe?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/routes.go:227 +0x336
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0006524a0?, {0x2529b30?, 0xc0004e88d8?}, 0x1f3be40?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x0?, {0x2529b30?, 0xc0004e88d8?}, 0xc0006524a0?, {0x251be60?, 0xc00008a720?})
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:388 +0x252
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x2529b30?, 0xc0004e88d8?}, 0x4d59d7?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:364 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005fb6c0?, {0x2529b30?, 0xc0004e88d8?}, 0xc0002f9d00?)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0002dd400, {0x2529b30, 0xc0004e88d8}, 0xc0002f9d00)
	github.com/caddyserver/caddy/v2@v2.6.4/modules/caddyhttp/server.go:300 +0xb66
net/http.serverHandler.ServeHTTP({0x1000?}, {0x2529b30, 0xc0004e88d8}, 0xc0002f9b00)
	net/http/server.go:2936 +0x316
net/http.initALPNRequest.ServeHTTP({{0x252b6c8?, 0xc0009ff110?}, 0xc0005c4380?, {0xc0003e4a50?}}, {0x2529b30, 0xc0004e88d8}, 0xc0002f9b00)
	net/http/server.go:3545 +0x245
net/http.(*http2serverConn).runHandler(0x25238d0?, 0x352c968?, 0x0?, 0x0?)
	net/http/h2_bundle.go:6049 +0x83
created by net/http.(*http2serverConn).processHeaders
	net/http/h2_bundle.go:5762 +0x68a
```

I'm not sure what's going on -- I assume it's panicking because the badger configuration is incorrect. It would be much easier to debug my configuration if there were an error message instead of a panic here.

**Comment by darkweak** [comment]
Hey @jvns thank you for this feedback. It didn't support empty `Dir` + `ValueDir` badger configuration option combined with the ÌnMemory` option. This commit https://github.com/darkweak/souin/pull/348/commits/606d64483c8648e4c5015f23b9f87700f0329bb1 should fix that.

**Comment by jvns** [comment]
thanks so much for the quick response!

This configuration also produces the same panic (and is what I was actually trying to do):

```
    cache {
        badger {
            configuration {
		    ValueThreshold 20000000
            }
        }
    }
```

Do you think the commit to souin would fix that panic as well? (I'm not sure how to rebuild caddy to test it myself)

**Comment by darkweak** [comment]
I tried your configuration with the fix and I get `http.handlers.cache     Impossible to open the Badger DB.Invalid ValueThreshold, must be less or equal to 1048576` in the logs.

With the instructions below you can try the fix on your side
```
# specific to your use case
xcaddy build --with github.com/darkweak/souin/plugins/caddy@6b17da1cf0274bbc66d164d55d479351870653d0 --with github.com/darkweak/souin@6b17da1cf0274bbc66d164d55d479351870653d0

# generic
xcaddy build --with github.com/{holder}/module@{commit_hash}
```

For Souin as Caddy module you have to override the `souin/plugins/caddy` hash to use and the `souin` dependency version used in the caddy `go.mod` because that's a monolith that contains both caddy module and the core code and the module refers to a tagged version of Souin core. (I don't know if I'm clear enough, let me know)

**Comment by jvns** [comment]
Thank you so much! I think I'll look into different caching software -- I definitely need to be able to cache responses bigger than 1MB (totally understood if that's not a supported use case).

**Comment by darkweak** [comment]
That's possible using `nutsdb` instead of `badger` but if you don't need an `InMemory` storage I recommend the `etcd` or `redis` storage.

**Comment by mholt** [comment]
Thanks for looking at this @darkweak :slightly_smiling_face: 

@jvns I'm a big fan of your blog and experiments, by the way. I would love it if Caddy could support your tinkering or projects!

**Comment by jvns** [comment]
(the thing I was looking into using Caddy for was Very Dumb, I just wanted to cache 1 value from 1 API endpoint, ended up just writing a 40-line Go program which uses a global variable as the cache instead :))

**Comment by mholt** [comment]
Ah :) Yeah I guess that point you might as well :laughing: 

Hopefully Caddy can serve you well next time :upside_down_face:
