### ISSUE TITLE
UNIX socket support for redis `url`

### ISSUE THREAD

**Issue by girlbossceo** [caddyserver/cache-handler#95]
Hi! I'd like to use UNIX sockets with redis and cache-handler. I don't see anything mentioning support for UNIX sockets and redis, but I tried it anyways with this syntax:
```
        cache {
                redis {
                        url unix//run/redis/redis.sock
                }
        }
```

This gives me a panic on Caddy restart/reload with:

```json
{
    "level": "info",
    "ts": 1721688515.9645174,
    "msg": "http: panic serving @: no alive address in InitAddress\ngoroutine 8825 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1903 +0xbe\npanic({0x2f754c0?, 0x4d7bf90?})\n\truntime/panic.go:770 +0x132\ngithub.com/darkweak/souin/pkg/middleware.NewHTTPCacheHandler({0x39fa4c8, 0xc00036f230})\n\tgithub.com/darkweak/souin@v1.6.49/pkg/middleware/middleware.go:66 +0x8ea\ngithub.com/caddyserver/cache-handler.(*SouinCaddyMiddleware).Provision(0xc00036f208, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc000e0f300, 0x3, 0x4}, {0x0, 0x0, ...}, ...})\n\tgithub.com/caddyserver/cache-handler@v0.13.0/httpcache.go:248 +0x18a\ngithub.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc000e0f300, 0x3, 0x4}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:369 +0x69b\ngithub.com/caddyserver/caddy/v2.Context.loadModuleInline({{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc004088500, 0x2, 0x2}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:419 +0xf0\ngithub.com/caddyserver/caddy/v2.Context.LoadModule({{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc004088500, 0x2, 0x2}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:200 +0x73e\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Route).ProvisionHandlers(0xc00314faa8, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc004088500, 0x2, 0x2}, {0x0, 0x0, ...}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/routes.go:154 +0x74\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.ProvisionHandlers({0xc00314f508, 0x15, 0x20?}, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc004088500, 0x2, 0x2}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/routes.go:209 +0xa6\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.Provision({0xc00314f508, 0x15, 0x25}, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc004088500, 0x2, 0x2}, ...})\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/routes.go:186 +0xbe\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).Provision(0xc0040884a0, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc004088500, 0x2, 0x2}, {0x0, 0x0, ...}, ...})\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/subroute.go:58 +0x7b\ngithub.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc004088500, 0x2, 0x2}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:369 +0x69b\ngithub.com/caddyserver/caddy/v2.Context.loadModuleInline({{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc001076430, 0x1, 0x1}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:419 +0xf0\ngithub.com/caddyserver/caddy/v2.Context.LoadModule({{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc001076430, 0x1, 0x1}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:200 +0x73e\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*Route).ProvisionHandlers(0xc002a98488, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc001076430, 0x1, 0x1}, {0x0, 0x0, ...}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/routes.go:154 +0x74\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.RouteList.ProvisionHandlers({0xc002a98008, 0x3a, 0x11507fa?}, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc001076430, 0x1, 0x1}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/routes.go:209 +0xa6\ngithub.com/caddyserver/caddy/v2/modules/caddyhttp.(*App).Provision(0xc0045cc0c0, {{0x39ea3b8, 0xc0020338f0}, 0xc002a757a0, 0xc003490000, {0xc001076430, 0x1, 0x1}, {0x0, 0x0, ...}, ...})\n\tgithub.com/caddyserver/caddy/v2/modules/caddyhttp/app.go:291 +0xd85\ngithub.com/caddyserver/caddy/v2.Context.LoadModuleByID({{0x39ea3f0, 0xc001039220}, 0xc002a757a0, 0xc003490000, {0xc001076430, 0x1, 0x1}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:369 +0x69b\ngithub.com/caddyserver/caddy/v2.Context.App({{0x39ea3f0, 0xc001039220}, 0xc002a757a0, 0xc003490000, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)\n\tgithub.com/caddyserver/caddy/v2/context.go:445 +0xf4\ngithub.com/caddyserver/caddy/v2.provisionContext.func3(...)\n\tgithub.com/caddyserver/caddy/v2/caddy.go:540\ngithub.com/caddyserver/caddy/v2.provisionContext(0xc00595a000?, 0x1)\n\tgithub.com/caddyserver/caddy/v2/caddy.go:545 +0x5e5\ngithub.com/caddyserver/caddy/v2.run(0x1000100?, 0x1)\n\tgithub.com/caddyserver/caddy/v2/caddy.go:400 +0x85\ngithub.com/caddyserver/caddy/v2.unsyncedDecodeAndRun({0xc005016000, 0xe43e6, 0xe6000}, 0x1)\n\tgithub.com/caddyserver/caddy/v2/caddy.go:343 +0x145\ngithub.com/caddyserver/caddy/v2.changeConfig({0x33a0442, 0x4}, {0x33a7f71, 0x7}, {0xc00557e000, 0xe43e6, 0x100000}, {0x0, 0x0}, 0x1)\n\tgithub.com/caddyserver/caddy/v2/caddy.go:234 +0x6b6\ngithub.com/caddyserver/caddy/v2.Load({0xc00557e000, 0xe43e6, 0x100000}, 0x1)\n\tgithub.com/caddyserver/caddy/v2/caddy.go:133 +0x236\ngithub.com/caddyserver/caddy/v2/caddyconfig.adminLoad.handleLoad({}, {0x39e23c0, 0xc002b1c990}, 0xc001590fc0)\n\tgithub.com/caddyserver/caddy/v2/caddyconfig/load.go:116 +0x51d\ngithub.com/caddyserver/caddy/v2.AdminHandlerFunc.ServeHTTP(0xc004415618?, {0x39e23c0?, 0xc002b1c990?}, 0xc004415580?)\n\tgithub.com/caddyserver/caddy/v2/admin.go:1299 +0x29\ngithub.com/caddyserver/caddy/v2.(*AdminConfig).newAdminHandler.func2.1({0x39e23c0, 0xc002b1c990}, 0xc001590fc0)\n\tgithub.com/caddyserver/caddy/v2/admin.go:240 +0x7b\nnet/http.HandlerFunc.ServeHTTP(0x39e2840?, {0x39e23c0?, 0xc002b1c990?}, 0x30e34a0?)\n\tnet/http/server.go:2171 +0x29\ngithub.com/caddyserver/caddy/v2.(*AdminConfig).newAdminHandler.func1.instrumentHandlerCounter.1({0x39e2840?, 0xc0026aa7e0?}, 0xc001590fc0)\n\tgithub.com/caddyserver/caddy/v2/metrics.go:47 +0x6f\nnet/http.HandlerFunc.ServeHTTP(0xc0020ce3d0?, {0x39e2840?, 0xc0026aa7e0?}, 0x148745f?)\n\tnet/http/server.go:2171 +0x29\nnet/http.(*ServeMux).ServeHTTP(0xc0020ce340?, {0x39e2840, 0xc0026aa7e0}, 0xc001590fc0)\n\tnet/http/server.go:2688 +0x1ad\ngithub.com/caddyserver/caddy/v2.adminHandler.serveHTTP({0xc0020ce340, 0x0, 0x1, {0xc000ed81c8, 0x3, 0x3}, 0x0}, {0x39e2840, 0xc0026aa7e0}, 0xc001590fc0)\n\tgithub.com/caddyserver/caddy/v2/admin.go:836 +0x55f\ngithub.com/caddyserver/caddy/v2.adminHandler.ServeHTTP({0xc0020ce340, 0x0, 0x1, {0xc000ed81c8, 0x3, 0x3}, 0x0}, {0x39e2840, 0xc0026aa7e0}, 0xc001590fc0)\n\tgithub.com/caddyserver/caddy/v2/admin.go:788 +0x7ea\nnet/http.serverHandler.ServeHTTP({0x39dcbd8?}, {0x39e2840?, 0xc0026aa7e0?}, 0x6?)\n\tnet/http/server.go:3142 +0x8e\nnet/http.(*conn).serve(0xc002130e10, {0x39ea3b8, 0xc00422c0f0})\n\tnet/http/server.go:2044 +0x5e8\ncreated by net/http.(*Server).Serve in goroutine 7716\n\tnet/http/server.go:3290 +0x4b4"
}
```

```

**Comment by Forza-tng** [comment]
Unix sockets are also slightly faster due to lower latency. I'd like to see Unix socket support too.

**Comment by darkweak** [comment]
The redis clients used are:
* go-redis
* rueidis

For go-redis we can use the configuration (as mentioned here https://github.com/redis/go-redis/issues/3)
```
        cache {
                redis {
                        configuration {
                                Addr /run/redis/redis.sock
                                Network unix
                        }
                        url unix//run/redis/redis.sock
                }
        }
```

rueidis support the unix socket as url `unix://run/redis/redis.sock`

I didn't tested by myself and that based on the issues/documentation of these redis clients.

**Comment by Forza-tng** [comment]
> The redis clients used are:
> 
> * go-redis
> * rueidis
> 

How do I specify to use `go-redis` instead of `rueidis`? The output from xcaddy shows both being compiled.

**Comment by darkweak** [comment]
@Forza-tng you can build with the master branch of Souin (that is the development repository) and use the refactored storages. 
```
--with github.com/darkweak/souin/plugins/caddy@master --with github.com/darkweak/souin@master --with github.com/darkweak/storages/go-redis/caddy
```
This will use the `go-redis` client to connect to your redis database.

**Comment by Forza-tng** [comment]
Thanks. It compiles well with xcaddy, however it does not use redis even though it parses the configuration (A wrong configuration leads to an error message).

It simply just says this:

```
{"level":"warn","ts":1723330520.2981198,"logger":"http.handlers.cache","msg":"You're running Souin with the default storage that is not optimized and for development purpose. We recommend to use at least one of the storages from https://github.com/darkweak/storages"}
```

**Comment by darkweak** [comment]
What's your configuration @Forza-tng ?
